### ISSUE TITLE
Create parser from Markdown to Slate and vice versa

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-markdown#10]
Initially we need to support markdown that is described by https://github.com/markdown-it/markdown-it/blob/master/lib/presets/default.js. 

- Heading h1 - h6
- Horizontal Rules
- Bold and italic text
- Strikethrough
- Unordered and ordered lists
- Code
- Tables
- Links
- Images
- Subscript
- Superscript
- Inserted text
- Marked text
- Definition lists
- Abbreviations

**P.S.** Own extensions like references (terms and products) will be covered separately

**Comment by asergeev-sc** [comment]
At the moment Rich Editor does not show cursor on UI in empty lines

**Comment by kvolkovich-sc** [comment]
For QA:

Open [this file](https://github.com/OpusCapita/react-markdown/blob/enhancement/10/src/client/components/MarkdownEditor/example.md) in GitHub editor and use it as reference of currently supported features.
