### ISSUE TITLE
Error appears if try unset numbering item list with highlighted item while climbing on previous string of text

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#102]
1. Create some numbered (of bulleted) item list;
2. make highlighting (bold or italic) of some item;
3. highlight by cursor whole list (climbing to previous string) and try to unset formation of list.
Result: `SCRIPT5007: Unable to get property 'firstChild' of undefined or null reference` appears for IE11. `TypeError: element is null` appears for FF.

**Comment by abaliunov-sc** [comment]
This bug is not reproduced on master branch in IE11 and FF
See [https://opuscapita.github.io/react-markdown/branches/master](https://opuscapita.github.io/react-markdown/branches/master).
