### ISSUE TITLE
Symbol for opening autocomplete list is transferred out the brace while inputting term or product in link

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#103]
1. Open Markdown Editor;
2. input default value for link: `[link text](http://example.com)`;
3. remove default value in text part of link: `[](http://example.com)`;
4. put cursor in text part of link and try to input term or product.
Result: symbol for opening autocomplete "$" ("#") is transferred out the text brace: `$[](http://example.com)`.

**Comment by abaliunov-sc** [comment]
Done.
See [https://opuscapita.github.io/react-markdown/branches/bug(slash)autocomplete-in-brace/(hash)103](https://opuscapita.github.io/react-markdown/branches/bug(slash)autocomplete-in-brace/(hash)103)
