### ISSUE TITLE
Remove toolbar buttons that are generated based on extensions

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-markdown#105]
Remove toolbar buttons that are generated based on configured extensions.

**Comment by abaliunov-sc** [comment]
Done.
See [https://opuscapita.github.io/react-markdown/branches/enhancement(slash)remove-extension-buttons/(hash)105](https://opuscapita.github.io/react-markdown/branches/enhancement(slash)remove-extension-buttons/(hash)105)
