### ISSUE TITLE
Hide full screen button by default and add new property "showFullScreenButton" (boolean) that enables/show it 

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-markdown#106]
Hide full screen button by default and add new property "showFullScreenButton" (boolean) that enables/show it

**Comment by abaliunov-sc** [comment]
Done.
See [https://opuscapita.github.io/react-markdown//branches/enhancement(slash)hide-fullscreen-button/(hash)106](https://opuscapita.github.io/react-markdown//branches/enhancement(slash)hide-fullscreen-button/(hash)106)
