### ISSUE TITLE
Add possibility to add/integrate additional/custom buttons in toolbar

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-markdown#107]
Add possibility to add own buttons to the toolbar. Add property **additionalButtons** (array of objects, where each object describes button) to _\<MarkdownInput/\>_. Each additional button as could be specified as an object with the following schema/structure:
```
{
    iconElement, // (React Element)
    label,  // (String, button text, usually in required language, optional)
    handleButtonPress, // function (optional) that is called on when the user presses the button, the function gets the object as a parameter (see description below) that contains the following info:
   // {
   //    value, // String, current markdown text inside the editor
   //    insertAtCursorPosition, // function that accepts object {chunk // String, additional markup} that could be called to update current markdown by inserting new chunk/text at current cursor position, if position is not available, then text is added to the end of markdown
   // }
}
```
If additional buttons are configured then we should render them on toolbar right aligned.
- If **icon** is not defined then no icon is rendered.
- If **label** is not defined then empty text ( "", string with 0 length) is rendered
- if **handleButtonPress** is not defined -> button press does not perform any action
- _insertAtCursorPosition_ function should be implemented inside markdown editor and provide described above functionality, initial use case is that user will be able to select term or product using reference search dialog and using this method reference to selected item will be added to current cursor position in markdown editor

**Comment by abaliunov-sc** [comment]
Done.
See [https://opuscapita.github.io/react-markdown/branches/enhancement(slash)additional-buttons/(hash)107](https://opuscapita.github.io/react-markdown/branches/enhancement(slash)additional-buttons/(hash)107)

Examples of use:

```
<div style={{ height: '70vh' }}>
  <MarkdownInput
    onChange={_scope.handleValueChange}
    value={_scope.state.markdownExample}
    readOnly={false}
    showFullScreenButton={true}
    locale='en'
    additionalButtons={[
      {
        iconComponent: (<i className="fa fa-search"></i>),
        handleButtonPress({ value, insertAtCursorPosition }) {
          setTimeout(() => {
            insertAtCursorPosition('#Product.new');    
          }, 100);             
        },
      },
      {
        handleButtonPress({ value, insertAtCursorPosition }) {
          insertAtCursorPosition('#Product.old');                 
        },
        label: 'Product'
      },
      {
        iconComponent: (<i className="fa fa-search"></i>),
        handleButtonPress({ value, insertAtCursorPosition }) {
          insertAtCursorPosition('$Term.new');                 
        },
        label: 'Term'
      }
    ]}
    extensions={[ ]}
  />
</div>

```
