### ISSUE TITLE
Action buttons (toolbar) in Plain markdown editor

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/react-markdown#11]
### Buttons (their groups, sequence)

\[B, I, S\] \[A\] \[H1, H2, H3, H4, H5, H6\], \[UL, OL\]
- inline text actions
  - \[B\] - bold mark
  - \[I\] - italic mark
  - \[S\] - strikethrough mark
- link
  - \[A\] - anchor insert
- text block actions 
  - \[H1\] - header 1 block
  - \[H2\] - header 2 block
  - \[H3\] - header 3 block
  - \[H4\] - header 4 block
  - \[H5\] - header 5 block
  - \[H6\] - header 6 block
- lists
  - \[UL\] - list block
  - \[OL\] - ordered list block

##### List [UL] button
Here is specification by video example for this button
![list-button-optimized](https://user-images.githubusercontent.com/24603787/28166906-5d5a7ad6-67e2-11e7-9dd6-5f054a7c3431.gif)

- Insert marker '* ' at the beginning of the line it line does not starts with ['{number}. ', '# ', '## ', '### ', '#### ', '##### ', '###### ']
- Replace with marker '* ' when line starts with  ['{number}. ', '# ', '## ', '### ', '#### ', '##### ', '###### ']
- Insert marker '* ' at the beginning of in the next line by enter at the end of the line that is marked as list item if item contain any text
- Clear line from '* ' and put cursor to a new line if user presses enter ant the end of the line that marked as list item but does not contain any text

- Ordered list [OL] button
Here is specification by video example for this button
![ordered-list-button-optimized](https://user-images.githubusercontent.com/24603787/28167332-ecdaa7e8-67e3-11e7-9da3-b41de506deed.gif)

  - Insert marker '1. ' at start in the line for not starts with ['* ', '# ', '## ', '### ', '#### ', '##### ', '###### ']
  - Replace with marker '1. ' when line starts with  ['* ', '# ', '## ', '### ', '#### ', '##### ', '###### ']
  - Insert marker '{number+1} ' at the beginning of in the next line by enter at the end of the line that is parked as list item if item contains any text
  - Clear line from '{number} ' and put cursor to a new line if user presses enter ant the end of the line that marked as ordered list item but does not contain any text
- Header item [h1-h6] buttons
Here is specification by video example for \[H2\] button (other header buttons work correspondingly)
![h2-button-optimized](https://user-images.githubusercontent.com/24603787/28199634-d3d3cbbc-686f-11e7-9fd6-3da0e41fe3b9.gif)

  - Insert marker '# ' - '###### ' (in depends on button) at start in the line for not stars with ['* ', '{number}. ']
  - Replace with marker '# ' - '###### ' (in depends on button) when line stars with ['* ', '{number}. ']
  - Remove existing header marker if corresponding header button is clicked
  - Update existing header marker to another header marker one is current header marker does not correspond to pressed header button

#### Marked elements
Here is specification by video example for these buttons
![bold-italic-strikethrough-optimized](https://user-images.githubusercontent.com/24603787/28200156-0128f076-6873-11e7-95cc-46944c548800.gif)

- Bold [B] button
  - Selected text is wrapped with with '\*\*', e.g.  {selected\_text} -> \*\*{selected_text}\*\*
  - Selected text if the text marked as bold is unwrapped, for example  \*\*{selected\_text}\*\* -> {selected\_text}
  - Inserts '\*\*{cursor}\*\*' into cursor position if text not selected, and cursor is placed inside
- Italic [I] button
  - Selected text is wrapped with with '\_', e.g.  {selected\_text} -> \_{selected_text}\_
  - Selected text if the text marked as italic is unwrapped, for example  \_{selected\_text}\_ -> {selected\_text}
  - Inserts '\_{cursor}\_' into cursor position if text not selected, and cursor is placed inside
- Strikethrough [S]  button
  - Selected text is wrapped with with '\~\~', e.g.  {selected\_text} -> \~\~{selected_text}\~\~
  - Selected text if the text marked as strikethrough is unwrapped, for example  \~\~{selected\_text}\~\~ -> {selected\_text}
  - Inserts '\~\~{cursor}\~~' into cursor position if text not selected, and cursor is placed inside

#### Inline elements
- External anchor [A] button
Here is specification by video example for this button
![link-button-optimized](https://user-images.githubusercontent.com/24603787/28200219-5d42085c-6873-11e7-9071-3140c8c2ad53.gif)

  - Wraps selected text with '\[' and '\](http://example.com)', for example {selected\_text} -> \[{selected\_text}\](http://example.com)
  - Inserts text \[link text\](http://example.com) into cursor position if text not selected.

**Notes**: 
- all use cases were taken from JIRA markdown editor
- in case of multi line selection toolbar buttons are not available (no action is supported)

**Comment by nstoliar-sc** [comment]
1. Input text:
> 

text
**bold**
_italic_
~~strike~~
[link](http://ga.jcatalog.com)
# T1
## T2
### T3
#### T4
##### T5
###### T6
1. number 1
* star
testing
> 
2. Insert marker '* ' at the beginning of the each line. 
Result: 'IndexSizeError: Index or size is negative or greater than the allowed amount' error appears for tenth inserting.

**Comment by ddivin-sc** [comment]
JS error 'IndexSizeError' was fixed

**Comment by nstoliar-sc** [comment]
Problems in IE browser:
1. Cursor always shifts spontaneously to start of string for bold, italic and strikethrough highlight. 
2. It is impossible to paste copyed information in markdown field. 
3. Wrong inputting of special symbols in middle of word:
- make bold (or italic, or strikethrough) highlight of some word by inputting of special symbols using buttons in panel; 
- remove highlight; 
- set cursor in middle of word; 
- input special symbols in middle of word by buttons in panel. 
Result: word is highlighted fully.
Expected result: special symbols are inputted in middle of word.

**Comment by ddivin-sc** [comment]
Fist problem will be fixed in separate issue.
Second and third are problems found in Slate

Issue about problem copy/past text into
https://github.com/ianstormtaylor/slate/issues/897
Issue about problem selected text
https://github.com/ianstormtaylor/slate/issues/946
