### ISSUE TITLE
Adjustment highlighting text in plain markdown editor

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/react-markdown#12]
Here is an example of markdown and its UI representation:

<img width="707" alt="screen shot 2017-07-14 at 10 35 47" src="https://user-images.githubusercontent.com/24603787/28202942-4180d244-6880-11e7-91e2-4569cab7e121.png">

What is important here is monospace font and separation of header/list markers from another text with invisible vertical line for better reading

**Comment by kvolkovich-sc** [comment]
**Implemented:**

* blockquote
* code (single tick)
* code (tripple ticks)
* code (single tilda)
* code (tripple tildas)
* header1
* header2
* header3
* header4
* header5
* header6
* hr
* list (single item)
* list (multiple items)
* url
* bold inside url
* italic inside url
* url inside italic
* url inside bold
* bold (underscores)
* bold (asterisks)
* italic (underscores)
  ```
  // uncompatible with markdown-it in case: `___italic__italic_`
  // should be `__<span class="token italic">_italic__italic_</span>`
  // now `<span class="token bold">___italic_italic__</span>italic_`
  ```

* italic (asterisks)

  ```
  // uncompatible with Commonmark in case: `**italic*italic*italic*`
  // should be `*<span class="token italic">*italic*italic*italic*</span>`
  // now `**italic<span class="token italic">*italic*</span>italic*`
  ```

* bold-italic (underscores)
* bold-italic (asterisks)
* bold-italic (underscores / asterisks mixed)
* strikethrough
* strikethrough inside italic
* strikethrough inside bold

**Not implemented yet:**

* code block
* italic inside strikethrough
* bold inside strikethrough
* url inside strikethrough

**Comment by nstoliar-sc** [comment]
1. Not implemented strikethrough in URL.
2. Not implemented Subscript which is made with tilda. Instead it blockquote is used. 
3. Numbers of numbered list is situated on one line with regular text.

**Comment by kvolkovich-sc** [comment]
1. Not implemented strikethrough in URL. **Fixed**
2. Not implemented Subscript which is made with tilda. Instead it blockquote is used. **Fixed**
3. Numbers of numbered list is situated on one line with regular text. **Fixed**

Uncompress attached archive and run index.html in browser to see how it works now.

[react-markdown-highlight.tar.gz](https://github.com/OpusCapita/react-markdown/files/1180092/react-markdown-highlight.tar.gz)

**Comment by nstoliar-sc** [comment]
Tested.

**Comment by kvolkovich-sc** [comment]
* italic inside strikethrough **Fixed**
* bold inside strikethrough **Fixed**
* url inside strikethrough **Fixed**
* url inside italic **Fixed**
* url inside bold **Fixed**

Uncompress attached archive and run index.html in browser to see how it works now.

[react-markdown-highlight.tar.gz](https://github.com/OpusCapita/react-markdown/files/1180222/react-markdown-highlight.tar.gz)

**Comment by nstoliar-sc** [comment]
Wrong displaying for next cases:

```
_**test**
*__test1__
_~~_test_~~
```

**Comment by kvolkovich-sc** [comment]
`_**test**` **Fixed**
`*__test1__` **Fixed**
`_~~_test2_~~` **Not fixed**
`_**~~test3~~**_` **Not fixed**
`___~~test4~~___` **Fixed**
`***~~test5~~***` **Fixed**
`*__~~test6~~__*` **Fixed**

Uncompress attached archive and run index.html in browser to see how it works now.

[react-markdown-highlight.tar.gz](https://github.com/OpusCapita/react-markdown/files/1182609/react-markdown-highlight.tar.gz)
