### ISSUE TITLE
Number of next item in numbered list is appear on current string after term or product input

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#120]
1. Open markdown editor;
2. input numbered or bulleted list;
3. put cursor in end of list and push 'Enter' button;
4. input '$' or '#', open autocomplete list;
5. using buttons on keyboard select necessary item and push 'Enter' button on keyboard.
Result: number or '*' symbol of next list item appears on current string.

![118](https://user-images.githubusercontent.com/25082017/35507697-b680d9e8-04fe-11e8-9f3a-fec38365822b.png)

**Comment by abaliunov-sc** [comment]
Done
