### ISSUE TITLE
Cursor loses focus in case if we insert a value using callback from the modal

### ISSUE THREAD

**Issue by skorsik-sc** [OpusCapita/react-markdown#121]
## React-Markdown Version
2.0.1

## Overview 
* **[Link to showroom](https://opuscapita.github.io/react-markdown/branches/2.0.1-DEV.PIM-12312/?currentComponentName=MarkdownInputModal&showSidebar=true)** where the issue can be reproduced
* https://github.com/OpusCapita/react-markdown/commit/53a1622046ed99af50ee42994999dfb6b7cacffb - commit with the added modal and all the related functionality
* **NOTE**: the provided implementation tried to reduce MarkdownInput updates (via state or other)

## How to reproduce
* select `MarkdownInputModal` component from the sidebar
* click `Show` button on the right
* in the appeared modal put cursor somewhere in the middle of the editor
* click the `Modal insert` button from the toolbar
* in the appeared modal click the `Paste Value and Close` button

## Expected result
* the second modal will disappear
* `BOOM!` value will be inserted in the cursors' position
* Cursor will **NOT** disappear and stay on the position right after the inserted value

**Comment by abaliunov-sc** [comment]
The component Modal which is used in a code uses animation at hiding. 
Focus is lost because of animation.
If during animation you insert the text in the editor, focus will be lost.
A function what inserts text has to be called after an animation.

If you use an animation, it isn't correct code:
```
  pasteValue = () => {
    insertAtCursorPosition("BOOM!");
    this.setState({ show: false });
  };
```

If an animation lasts for 400 milliseconds you should use that code for example:
```
  pasteValue = () => {
    this.setState({ show: false });

    setTimeout(() => {
      insertAtCursorPosition("BOOM!");
    }, 500)
  };
```

**Comment by skorsik-sc** [comment]
Thank you for the explanation!
