### ISSUE TITLE
"ReferenceError: self is not defined"

### ISSUE THREAD

**Issue by dijs** [OpusCapita/react-markdown#125]
trying to run with React 16

**Comment by kvolkovich-sc** [comment]
Thanks. We'll take a look.

**Comment by dsanko-sc** [comment]
Not reproduced.

**Comment by kvolkovich-sc** [comment]
Confirm. Can't reproduce the issue.

Can you provide any additional information? 

React and @opuscapita/react-markdown versions, console message, browser name/versions, place in code?
