### ISSUE TITLE
Updating slate.js

### ISSUE THREAD

**Issue by Nes-si** [OpusCapita/react-markdown#128]
Do you have any plans to update slate.js and other libs to its actual versions?
Now I have a lot of warnings when I install it in my project (React v16.3). I think these can be cause a number of unexpected bugs.
```
npm WARN slate@0.24.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN slate-base64-serializer@0.1.22 requires a peer of slate@^0.28.2 but none is installed. You must install peer dependencies yourself.
npm WARN slate-prop-types@0.1.13 requires a peer of slate@^0.26.1 but none is installed. You must install peer dependencies yourself.
npm WARN slate-react@0.1.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN slate-react@0.1.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by kvolkovich-sc** [comment]
Hi, @Nes-si!

Take a look at [slate changelog](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md)

At current time, each minor version has breaking changes.
While slate API is so unstable, there is no much sense to spent resources.

If you'll report specific bugs in `@opuscapita/react-markdown`, ofcourse we'll fix them. 

PRs are welcome also!)

**Comment by Nes-si** [comment]
Ok, that's how I see your editor in my project:
![mkdown](https://user-images.githubusercontent.com/5188972/38932424-cdf78ef6-431e-11e8-8425-b6bda9100d18.png)
Pretty nice.

**Comment by kvolkovich-sc** [comment]
Beautiful. Say hello to global styles of Twitter Bootstrap)

I share your pain. Unfortunately, I can not influence it at this moment.
