### ISSUE TITLE
Add loading indicator and optional trailing space for autocomplete, and hideable toolbar 

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-markdown#130]
TODO: 

- [x] Show `Searching <spinner>` while extensions resolve data. Currently `No matches found` is shown in this case, which is irrelevant if extension is currently fetching data.
- [x] Remove default trailing space in extensions.
- [x] Add possibility to hide toolbar.
- [x] Introduce `renderItem` function (optional) which returns a component to render an item in autocomplete widget.

**Comment by dshienok-sc** [comment]
Additional release: [grails-markdown](https://github.com/OpusCapita/grails-markdown/releases/tag/v8.2.GA.20)
