### ISSUE TITLE
Selecting newline sign disables formatting buttons in markdown editor in Edge browser. 

### ISSUE THREAD

**Issue by mpritchin-sc** [OpusCapita/react-markdown#137]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 3h
Remaining Estimation | 0h

## Overview
Selecting newline sign disables formatting buttons on markdown toolbar in Edge browser, please, see [attachment](https://user-images.githubusercontent.com/36260939/41616254-37d96908-7406-11e8-8eee-f1c1d7adea60.gif). Can be simply reproduced via `Shift`+`Home` key combination. 

## Preconditions
Microsoft Edge version: **42.17134.1.0**
User is using Edge browser.
User is logged into PIM.
There is a markdown attribute created in the installation.

## Steps to Reproduce
1. Open `Product Search` page
2. Create any product 
3. Open newly created product on `Product Editor` page on `Attributes` tab
4. Press `New` button and add a markdown attribute
5. Edit value of added attribute with provided text below:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
Quisque interdum mattis justo sit amet facilisis. 
Sed ultricies, sapien sed dignissim blandit, sapien felis tristique dolor, sed condimentum purus nulla eu diam. 
6. Select the first and the second lines of text (can be performed with the use of mouse, or by using hotkey combinations).

## Actual Result
Markdown toolbar formatting buttons got disabled until newline sign is deselected.

## Expected Result
Markdown toolbar formatting buttons are enabled.

## Bypass possibility
User can still use hotkeys mapped to the markdown toolbar formatting buttons.

Original issue: https://github.com/OpusCapita/pimline/issues/404

**Comment by estambakio-sc** [comment]
[Link for QA](https://opuscapita.github.io/react-markdown/branches/issue-137/index.html?currentComponentName=MarkdownInput)

**Comment by nstoliar-sc** [comment]
We don't support multi string highlight. Won't fix.
