### ISSUE TITLE
Entered characters are not displayed

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-markdown#142]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | ???h
Remaining Estimation | ???h

Initial issue: https://github.com/OpusCapita/minsk-core-externals/issues/148

**Comment by estambakio-sc** [comment]
QA: you can find fixed version on `pim`'s `FDD.markdown-142` branch.

**Comment by dshwedovsky-sc** [comment]
Checked for PIM 0.0.1-markdown-142-SNAPSHOT for markdown attribute multilanguage and non-multilanguage.
In described usecase after deleting term as value, in next time it is possible to enter new term
