### ISSUE TITLE
Values are incorrectly entered in markdown editor opened in modal dialog

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#150]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | ???h
Remaining Estimation | ???h

1. Open modal markdown editor;
2. input some value into markdown; -> value is not input
3. click second time into markdown;
4. input value into markdown.
Result: entered early value appears, new values are set in front of early entered values.

**Comment by kvolkovich-sc** [comment]
@nstoliar-sc, please test:

https://opuscapita.github.io/react-markdown//branches/issue-150-focus/index.html?currentComponentName=MarkdownInputModal&showSidebar=true

Most changes are related to autocomplete. 
Please pay attention to autocomplete behavior.

**Comment by nstoliar-sc** [comment]
Product autocomplete (via '#') hasn't highlighted value in list. 
![318](https://user-images.githubusercontent.com/25082017/45163906-047c5e80-b1fa-11e8-9074-24280ddd7095.png)

**Comment by kvolkovich-sc** [comment]
> Product autocomplete (via '#') hasn't highlighted value in list. 

Fixed

opuscapita.github.io/react-markdown//branches/issue-150-focus/index.html?currentComponentName=MarkdownInputModal&showSidebar=true

**Comment by nstoliar-sc** [comment]
Tested. Values are inputted correct into markdown. Please, merge with master branch.
