### ISSUE TITLE
Don't emit onChange if text is not actually changed

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-markdown#152]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 4h
Remaining Estimation | 0h

Current behavior: `onChange` is emitted if cursor position changes.

Desired behavior: `onChange` emits only if text is changed.

P.S. also 
- remove `color` parameter in extensions example/docs, as it is obsolete.
- remove `objectClassName` from `extensions` docs as obsolete.

**Comment by estambakio-sc** [comment]
Link for QA: https://opuscapita.github.io/react-markdown/branches/issue-152/?currentComponentName=MarkdownInput

**Comment by nstoliar-sc** [comment]
Tested. 'handleValueChange' is not called if text was not changed. Please, merge with master branch.

**Comment by estambakio-sc** [comment]
Also released `grails-markdown` @8.10.GA.3
