### ISSUE TITLE
Autocomplete list is partially hidden in markdown with little size 

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#160]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 4h
Remaining Estimation | 0h

Autocomplete list is partially hidden in markdown with little size. Problem is reproduced in FF and Chrome.

![339](https://user-images.githubusercontent.com/25082017/46866807-84b26700-ce2b-11e8-8ca4-cb1ec56ccb6d.png)

**Comment by estambakio-sc** [comment]
@nstoliar-sc please check if this is still the case: https://opuscapita.github.io/react-markdown//branches/master/index.html?currentComponentName=MarkdownInput

**Comment by nstoliar-sc** [comment]
Tested. Autocomplete list is displayed correctly in markdown with little size. Please, merge with master branch.
