### ISSUE TITLE
Bad positionong of the term/product autocomplete dialog

### ISSUE THREAD

**Issue by apolishchuk-sc** [OpusCapita/react-markdown#161]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 8h
Remaining Estimation | 0h

### Overview
The positioning of product/term autocomplete is bad in the following cases:
 * In the Markdown editor you start entering the reference to term and then click outside the area, the autocomplete dialog is re-positioned, see e.g.:

![image](https://user-images.githubusercontent.com/24775759/47085887-b4dd7980-d220-11e8-99ea-aebb98da55a5.png)

 * In the text-table area (text view) you start entering reference to product the dialog overlaps entered values (in case of a large number of available values), see

![image2](https://user-images.githubusercontent.com/24775759/47085895-b9099700-d220-11e8-9234-5da2f7a36ae8.png)

**Comment by estambakio-sc** [comment]
Demo for Modal: https://opuscapita.github.io/react-markdown//branches/issue-161-modal-in-modal/index.html?currentComponentName=MarkdownInputModal&showSidebar=true

**Comment by nstoliar-sc** [comment]
If user starts input autocomplete value the Markdown pop-up in IE, then tries to close pop-up, and click on 'cancel' button, cursor could not be set in Markdown.

**Comment by nstoliar-sc** [comment]
If user starts input autocomplete value the Markdown pop-up in Firefox, then tries to close pop-up, and click on 'cancel' button, cursor could not be set in Markdown.

**Comment by estambakio-sc** [comment]
@nstoliar-sc this is fixed, please check it.

**Comment by nstoliar-sc** [comment]
Tested. Autocomplete dialog is not re-positioned if markdown pop-up is being closed. Cursor is set correctly in markdown if user reject closing. Autocompletes in text-table (text view) are displayed correctly. Please, merge with master branch.
