### ISSUE TITLE
Markdown/Text-Table Editor isn't Working Correctly with Term Replacement

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-markdown#163]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 8h
Remaining Estimation | 8h

https://github.com/OpusCapita/minsk-core-externals/issues/380

**Comment by estambakio-sc** [comment]
Demo: https://opuscapita.github.io/react-markdown//branches/issue-163/index.html?currentComponentName=MarkdownInput

**Comment by nstoliar-sc** [comment]
1. Open markdown;
2. set cursor in some place of markdown;
3. click on 'Enter' on keyboard, make empty line;
4. click on 'Enter' on keyboard again, input `$` or `#` and select some item in autocomplete list.
Result: empty line is cut.
Expected result: empty line is stayed after selecting term or product on next line.

**Comment by estambakio-sc** [comment]
@nstoliar-sc this is fixed, please test again.

**Comment by nstoliar-sc** [comment]
Markdown editor is not opened in IE.
![38](https://user-images.githubusercontent.com/25082017/63340357-83a56c80-c34f-11e9-95f3-cbd3950a1ab1.png)

**Comment by nstoliar-sc** [comment]
Tested. Terms and Products are changed according selected item in autocomplete without residual symbols from previous term or product. Please, merge with master branch.
