### ISSUE TITLE
Autocomplete in modal closes on click on scroll bars

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-markdown#167]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 8h
Remaining Estimation | 0h

https://github.com/OpusCapita/minsk-core-externals/issues/608

**Comment by estambakio-sc** [comment]
Can be reproduced on `master` branch: [link](https://opuscapita.github.io/react-markdown/branches/master/index.html?currentComponentName=MarkdownInputModal&showSidebar=true) type `#`, click on scroll - autocomplete disappears

Fixed here: [link](https://opuscapita.github.io/react-markdown/branches/issue-167/index.html?currentComponentName=MarkdownInputModal&showSidebar=true)

**Comment by nstoliar-sc** [comment]
1. It is neseccary twice click on scroll to make scrolling in IE.
![18](https://user-images.githubusercontent.com/25082017/79388956-dbe04d00-7f76-11ea-853f-86cebf27b998.gif)

2. Long value is displayed partially in autocomplete list in case displaying only one this value in list.
![43](https://user-images.githubusercontent.com/25082017/79388861-c5d28c80-7f76-11ea-8ed2-e1f47de8c7f9.png)

**Comment by estambakio-sc** [comment]
@nstoliar-sc 2) is fixed, please test it

**Comment by nstoliar-sc** [comment]
Tested. Autocomplete select for markdown works correctly. Please, merge with master branch.
