### ISSUE TITLE
Incorrect behavior of the Rich Editor when a line break

### ISSUE THREAD

**Issue by abaliunov-sc** [OpusCapita/react-markdown#19]
Bugs checklist :

---

- [ ] **How reproduce:** scroll to **Indented code** mouse click to end of code block,
 press<kbd>Return</kbd>.

![bug2](https://user-images.githubusercontent.com/24652543/28627687-3bcd7758-722b-11e7-9eda-a0ba4a37218e.gif)

**Current behavior:** new empty code block added
**Expected behavior:** old code block should increase in size

---

- [ ] **How reproduce:** scroll to **Lists** mouse click to end of one of first-level list item,
 press <kbd>Return</kbd>.

![bug3](https://user-images.githubusercontent.com/24652543/28627842-97fe6bfe-722b-11e7-98b0-9a4a535be099.gif)

**Current behavior:** new child list item added with two bullets 
**Expected behavior:** new child list item added with one bullet

---

- [ ] **How reproduce:** scroll to **Definition lists** mouse click to end of **Term1** press <kbd>Return</kbd>, then press <kbd>Return</kbd> again.

![bug4](https://user-images.githubusercontent.com/24652543/28628010-120fd16c-722c-11e7-957a-4e6a40552004.gif)

**Current behavior:** new line added after **second** <kbd>Return</kbd> press
**Expected behavior:** definition list item added after **first** <kbd>Return</kbd> press

**Comment by asergeev-sc** [comment]
Rich editor is not actual any more for the moment
