### ISSUE TITLE
PlainMarkdownEditor highlighting not working properly in some cases

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-markdown#21]
`_~~_test2_~~`
`~~_test2_~~_`
`~~*test2*~~*`
`*~~*test2*~~`

Not working as expected

**Comment by abaliunov-sc** [comment]
****asasasa**
Not working as expected

**Comment by kvolkovich-sc** [comment]
Remark from @nstoliar-sc :

If we try to input follow values in markdown, styles will not work correctly:
*test (value should be bold);
_ test (value should be bold and italic);
test (value should be bold);
test1 testing test2 (value "testing" should not be strikethrough).

**Comment by abaliunov-sc** [comment]
As the tokenizer will be used the module [markdown-it](https://github.com/markdown-it/markdown-it) as he produces correct division into tokens and has convenient api

**Comment by nstoliar-sc** [comment]
New problem was found. If we use Italic two times in text, all words between Italic highlighted values became Italic. For, example: \_test\_ testing \_test\_.

**Comment by abaliunov-sc** [comment]
Done
