### ISSUE TITLE
Refactor toolbar buttons

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-markdown#26]
Now each button in toolbar has own react component.

**ItalicButton.js**

```
<OverlayTrigger placement="bottom" overlay={<Tooltip id="italic-tp">Italic (Ctrl+I)</Tooltip>}>
    <button className={classnames('btn btn-default', { active })} disabled={disabled || hasMultiLineSelection(state)}
      onClick={e => onChange(active ? unwrapItalicMarkdown(state) : wrapItalicMarkdown(state))}
    >
      <i className="fa fa-italic"/>
   </button>
</OverlayTrigger>
```

Better way is define button component in one place.

Also we can avoid `react-bootstrap` dependency by removing  `<OverlayTrigger />` button wrapper and pass tooltip text as standard html `title=""` attribute.

**Comment by abaliunov-sc** [comment]
Done
[See](https://opuscapita.github.io/react-markdown//branches/enhancement(slash)buttons/(hash)26/)
