### ISSUE TITLE
Rename module and components

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-markdown#31]
- Let's rename **MarkdownEditor** component to **MarkdownInput** it will reflect its usage as it is just another input control on a form. **Editor** usually reflects name for full featured object editor (Whole UI/functionality). So correspondingly let's rename **PlainMarkdownEditor** component to **PlainMarkdownInput**.
- Let's also revert back module/repository name to **react-markdown**

**Comment by kvolkovich-sc** [comment]
Done.
