### ISSUE TITLE
react and react-dom are not externalized from MarkdownInput.js file that is packaged into Grails plugin

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-markdown#38]
It looks like Slate and/or its dependencies lead to the situation when web pack is not able to 'extract' _react_ and _react-dom_  from result bundle

**Comment by kvolkovich-sc** [comment]
Fixed after update to new `slate` version in https://github.com/OpusCapita/react-markdown/pull/49

Final bundle size is 533 KB
