### ISSUE TITLE
"react" and "react-dom" appears in final bundle

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-markdown#39]
## Benefit:

661KB / 167KB gzipped **vs** 492KB / 112KB gzipped

**Comment by kvolkovich-sc** [comment]
Properly working solution doesn't found.

**Comment by asergeev-sc** [comment]
Proposed solution does not work as in this case additional libraries are expected to be globally available too like _Immutable_. If you run `npm start` you'll get exception(s) in browser:
```
Uncaught TypeError: Cannot read property 'Map' of undefined
    at Object.102.../constants/model-types (index.js:10585)
    at s (index.js:2882)
    at index.js:2882
    at Object.141.../models/block (index.js:24004)
    at s (index.js:2882)
    at index.js:2882
    at Object.103.../utils/generate-key (index.js:10715)
    at s (index.js:2882)
    at index.js:2882
    at Object.101.../constants/model-types (index.js:10350)
```

**Comment by kvolkovich-sc** [comment]
https://github.com/ianstormtaylor/slate/issues/1014#issuecomment-328735232

**Comment by kvolkovich-sc** [comment]
Fixed after update to new `slate` version in https://github.com/OpusCapita/react-markdown/pull/49
