### ISSUE TITLE
Add PlainMarkdownEditor component

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-markdown#4]
Content looks like simple plain text (pure markdown). 

It should be done using [slate](http://slatejs.org//) 

| Name                           | Type                     | Description         |
| ------------------------------ | :----------------------  | -----------------------------------------------------------|
| onChange | func | markdown => {} |
| value | string | raw markdown representation |

Note: Later add markdown syntax highlighting and control buttons

**Comment by asergeev-sc** [comment]
Not completed functionality
- *value* is not implemented
- *onChange* is not called
- something wrong with "textarea/editor" styles, also when user do mouse click inside editor curssor is not places inside (no focus)
- By default MarkdownEditor should render PlainMarkdownEditor and pass incoming *value* and *onChange* props through.

**Comment by dsanko-sc** [comment]
Ctrl + A and Shift + Home work incorrectly after item select.

**Comment by asergeev-sc** [comment]
Hide all buttons
