### ISSUE TITLE
Could not position cursor to the Markdown Input if value is empty.

### ISSUE THREAD

**Issue by hvalkova-sc** [OpusCapita/react-markdown#41]
Steps to reproduce:
1. Delete all the text from Markdown Input
2. Click somewhere outside
3. Click back on Markdown Input editable area

=> Could not position cursor to start typing text

**Comment by kvolkovich-sc** [comment]
Fixed and released. You can check it fast here: https://opuscapita.github.io/react-markdown/

**Comment by hvalkova-sc** [comment]
Thank you!
