### ISSUE TITLE
Wrong working of markdown in follow cases

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#44]
If we try to input follow values in markdown, styles will not work correctly:
\*\*\*test\*\* (value should be bold);
\_ \_\*\*test\*\*\_ (value should be bold and italic);
\*\*_\_test\_\_\*\* (value should be bold);
\~\~test1\~\~ testing \~\~test2\~\~ (value "testing" should not be strikethrough).

**Comment by kvolkovich-sc** [comment]
Moved to: https://github.com/OpusCapita/react-markdown/issues/21
