### ISSUE TITLE
On Blur error in IE11

### ISSUE THREAD

**Issue by hvalkova-sc** [OpusCapita/react-markdown#47]
In IE exception occurs on blur.
Steps to reproduce in demo app:
1. Select some text in Markdown Input
2. Click somewhere outside, e.g. Sidebar button
![markdowninput_onblur_error](https://user-images.githubusercontent.com/25081403/30328831-2ff4d9e8-97d9-11e7-9f9c-4b49f7d76403.png)

The same is reproduced if to use Markdown Input inside the Modal.
See example on branch https://github.com/OpusCapita/react-markdown/tree/1.0.3-DEV.PIM-11845
1. Select some text in Markdown Input
2. Click on Modal 'x' button or outside the modal
![markdowninput_in_modal](https://user-images.githubusercontent.com/25081403/30329020-c24244fc-97d9-11e7-81a2-8a84f2d07675.png)

The exception occurs because of https://github.com/OpusCapita/slate/ -> src/components/content.js:254
```
    const el = target.nodeType === 3 ? target.parentElement : target
    return (
      (el.isContentEditable) &&
      (el === element || findClosestNode(el, '[data-slate-editor]') === element)
    )
```
It seems that **target.parentElement** needs to be replaced by **target.parentNode**.

**Comment by kvolkovich-sc** [comment]
@hvalkova-sc Can u make a pull request with solution to slate repo?)

**Comment by kvolkovich-sc** [comment]
Fixed in https://github.com/OpusCapita/react-markdown/pull/49
