### ISSUE TITLE
Add support for markdown extensions: product and term references

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-markdown#5]
## Intro

Add support for markdown extensions: product and term references

You can find markdown extension/plugin spec here: http://buildserver.jcatalog.com/gitweb/?p=js-markdown.git;a=blob;f=README.md;h=b0e55e3bd8e0fea97b62a1a4e8f60fd05ef1831b;hb=HEAD

## How UI should work

*PlainMarkdownEditor*
Text is shown as it is like: #productid or $termid without changes. For each autocomplete we need specific toolbar button. Example"product" (some icon or text) if user clicks on it at current cursor position in editor corresponding prefix (#) is added and cursor set right after it (e.g. autocomplete is displayed automatically and user can use it)

*RichMarkdownEditor*
We need to show existing references as separate visual block (as first solution, similar to github issue labels UI representation) E.g. we take whole text after # or $ and show it as bootstrap alert with close/dismiss icon (http://getbootstrap.com/components/#alerts-examples). E.g. whole block could be removed at once (text is not editable inside) wither by clicking close icon or by backspace key.

**Comment by asergeev-sc** [comment]
Describe how to configure each autocomplete.
Simple/first approach could be:
Introduce **autocompletes** property with defines list/array of available autocompletes. Each autocomplete could be described in the following way:
```
{
  matcher: <regex>
  fetcher: function({term}) // return array where each item is object which contains '_objectLabel'
}
```

todo: finish

**Comment by asergeev-sc** [comment]
Autocompletes should be supported in RichMarkdownEditor and PlainMarkdownEditor but in a different way.

*PlainMarkdownEditor*
Text is shown as it is like: #productid or $termid without changes. For each autocomplete we need specific toolbar button. Example"product" (some icon or text) if user clicks on it at current cursor position in editor corresponding prefix (#) is added and cursor set right after it (e.g. autocomplete is displayed automatically and user can use it)

*RichMarkdownEditor*
We need to show existing references as separate visual block (as first solution, similar to github issue labels UI representation) E.g. we take whole text after # or $ and show it as bootstrap alert with close/dismiss icon (http://getbootstrap.com/components/#alerts-examples). E.g. whole block could be removed at once (text is not editable inside) wither by clicking close icon or by backspace key.

**Comment by dsanko-sc** [comment]
Markdown extensions API example:
```
extensions = [
      {
             specialCharacter: '$',
             regex: /\$\w*$/,
             searchItems: (term) => {
                   return Promise.resolve([])
             },
             plainMarkdownText: (item) => {
                   return '$' + item._objectLabel
             },
             richMarkdownText: (item) => {
                   return '<span>' + item._objectLabel + '</span>'
             }
      }
]
```

**Comment by dsanko-sc** [comment]
On click behaviour of buttons which add references to objects ('Product', 'Term', etc.):

1. In PlainMarkdownEditor:

When caret is inside, in the start or end of word then insert special character before this word and stay caret in the current word position. If caret is in the end of string then insert special character at last string position separated with space from last word. If current caret position is surrounded with spaces then special character is inserted in this position.

2. In RichMarkdownEditor:

When caret is inside of the word then split this word into two different words and insert block of selected item between these words. If caret is in the start or end of the word then insert block before or after word correspondingly.

**Comment by dsanko-sc** [comment]
Bugs:
Firefox:
1. After adding object reference it has focus (caret is in uneditable text) and on keyboard input text it is replaced with those text.
2. On keyboard arrows left/right caret is appeared in uneditable text of object reference.
3. Caret before inserted object reference is not displayed.
Chrome:
1. If object reference is the first/single element in line and caret is before it, then after pressing keyboard arrow right caret is not displayed.
2. If object reference is last/single element in line and caret is after it, then after pressing keyboard arrow left caret is not displayed.

**Comment by kvolkovich-sc** [comment]
Done for plain mode.
> Rich mode is not supported now https://github.com/OpusCapita/react-markdown/issues/25

**Comment by kvolkovich-sc** [comment]
Please test.

Uncompress attached archive and run index.html in browser to see how it works now.

[react-markdown.tar.gz](https://github.com/OpusCapita/react-markdown/files/1211469/react-markdown.tar.gz)

**Comment by nstoliar-sc** [comment]
Tested. If some symbol stands before # or $, product or term autocomplete doesn't appear. Else problems not found.
