### ISSUE TITLE
Read-only mode for MarkdownInput

### ISSUE THREAD

**Issue by hvalkova-sc** [OpusCapita/react-markdown#50]
Please add possibility to make MarkdownInput read-only by passing additional parameter.
The MarkdownInput in read-only mode could be _without toolbar_,
and area with text is not editable, but text could be selected and copied.
Could be implemented by adding parameter to slate editor:
```
<Editor
   readOnly={true}
   ...
/>
```

**Comment by kvolkovich-sc** [comment]
Implemented here: https://github.com/OpusCapita/react-markdown/pull/51
Please check here https://opuscapita.github.io/react-markdown/ and close the issue if OK.
