### ISSUE TITLE
Remove text indentation on the left

### ISSUE THREAD

**Issue by hvalkova-sc** [OpusCapita/react-markdown#52]
Please remove margin on the left.
See mockup
![markdown_without_indentation](https://user-images.githubusercontent.com/25081403/30971378-6298b6dc-a470-11e7-9d6c-edaa6761310c.png)

**Comment by kvolkovich-sc** [comment]
Fixed. Demo here: https://opuscapita.github.io/react-markdown/remove-left-offset/index.html?currentComponentId=%40opuscapita%2Freact-markdown%2F1.1.3%2FMarkdownInput

**Demo is temporary available!**

**Comment by hvalkova-sc** [comment]
Checked, works as expected.

**Comment by kvolkovich-sc** [comment]
Fixed
