### ISSUE TITLE
Autocomplete widget dissapears on scrollbars click when used inside Modal.

### ISSUE THREAD

**Issue by hvalkova-sc** [OpusCapita/react-markdown#56]
In case MarkdownInput is rendered inside Bootstrap Modal,
and label for autocomplete item is too long :
Created demo example on branch 1.1.2-DEV.PIM-11848

Steps to reproduce:
Revert branch changes in _AutocompleteContainer_ first
_1_
1. Type $ 
2. Try to scrolll horizontal bar of the autocomplete widget

_2_
1. Type $ when cursor is close to the end of line
2. Try to scrolll horizontal bar of the editor.

It seems .modal-open is stealing focus and PlainMarkdownInput.handleChange is triggered.

Note:
If to type $ second time - item is inserted immediately (not showing autocomplete widget).

![markdown_scrollbars](https://user-images.githubusercontent.com/25081403/31082090-9801ae72-a796-11e7-8e21-9a8cdbbfc9f3.png)

**Comment by abaliunov-sc** [comment]
Move autocomplete widget to left side if it left beyond the right border
[See](https://opuscapita.github.io/react-markdown/bug%252Fautocomplete%252F%252356/index.html)

**Comment by abaliunov-sc** [comment]
Replacement of long item on short with dots (...)

**Comment by kvolkovich-sc** [comment]
Please check in Autocomplete if **Firefox**. It don't works as expected.

Can you use CSS rule `text-overflow: ellipsis` and `max-width` or even fixed `width` to fix long items issue? https://css-tricks.com/almanac/properties/t/text-overflow/
Compare three dots vs ellipsis character:  `...`  vs `…`

**Comment by abaliunov-sc** [comment]
Three dots changed on ellipsis
The behavior of an autocomplete  in IE11 is corrected
[See](https://opuscapita.github.io/react-markdown/bug%252Fautocomplete%252F%252356/index.html)

**Comment by hvalkova-sc** [comment]
Checked.

**Comment by kvolkovich-sc** [comment]
Fixed
