### ISSUE TITLE
Autocomplete widget rendered down (and right scrollbar not working) if close to bottom in some cases.

### ISSUE THREAD

**Issue by hvalkova-sc** [OpusCapita/react-markdown#58]
Steps to reproduce
1. Delete all the text under third 'opuscapita' link
2. On the next line after third 'opuscapita' link enter '$'
=> widget rendered down and right scroll bar not working.
![autocomplete_widget](https://user-images.githubusercontent.com/25081403/31172888-00ec67ec-a90e-11e7-8b6d-e418e270a711.png)

**Comment by asergeev-sc** [comment]
It looks like autocomplete should be rendered not inside the "editor area". The same is true for drop down menu used for headers.

**Comment by abaliunov-sc** [comment]
1. Fix bug widget's position
2. When widget show editor's scroll hide, when widget hide editor's scroll show

[See simple editor](https://opuscapita.github.io/react-markdown//branches/bug(slash)autocomplete-2/(hash)58/?currentComponentId=%40opuscapita%2Freact-markdown%2F1.1.5%2FMarkdownInput)
[See editor in modal mode](https://opuscapita.github.io/react-markdown//branches/v1.1.2-DEV.PIM-11848(slash)(hash)58/?currentComponentId=%40opuscapita%2Freact-markdown%2F1.1.3-DEV.PIM-11848%2FMarkdownInput)

Done

**Comment by abaliunov-sc** [comment]
Done
[See](https://opuscapita.github.io/react-markdown//branches/bug(slash)autocomplete-2/(hash)58/?currentComponentId=%40opuscapita%2Freact-markdown%2F1.1.8%2FMarkdownInputModal&showSidebar=true)

**Comment by hvalkova-sc** [comment]
Checked.
