### ISSUE TITLE
The tooltip is hidden

### ISSUE THREAD

**Issue by jminich-sc** [OpusCapita/react-markdown#61]
![screenshot1](https://user-images.githubusercontent.com/25081565/31231319-33e36dd0-a9ef-11e7-8c9f-d84b9acdec44.png)

**Comment by abaliunov-sc** [comment]
Done
[See](https://opuscapita.github.io/react-markdown//branches/bug(slash)tooltip/(hash)61/?currentComponentId=%40opuscapita%2Freact-markdown%2F1.1.8%2FMarkdownInputModal&showSidebar=true)
