### ISSUE TITLE
The new line is not shown after pressing on enter

### ISSUE THREAD

**Issue by jminich-sc** [OpusCapita/react-markdown#62]
**Steps to reproduce:**

1. Go to the bottom of the page
2. Press on the enter on the keyboard

**Expected result:** the new line is shown

**Actual result:**  the new line is shown only after scrolling down

**Comment by abaliunov-sc** [comment]
Done for new line in the page's bottom.
[see](https://opuscapita.github.io/react-markdown//branches/bug(slash)new-line/(hash)62/?currentComponentId=%40opuscapita%2Freact-markdown%2F1.1.5%2FMarkdownInput)

**Comment by abaliunov-sc** [comment]
Done for insert text in the page's bottom
[see](https://opuscapita.github.io/react-markdown//branches/bug(slash)new-line/(hash)62/index.html?currentComponentId=%40opuscapita%2Freact-markdown%2F1.1.5%2FMarkdownInput)

**Comment by kvolkovich-sc** [comment]
Fixed.
