### ISSUE TITLE
No internationalization

### ISSUE THREAD

**Issue by apolishchuk-sc** [OpusCapita/react-markdown#66]
We need to implement internationalization and add German translations for the following tooltips/messages:

Insert header = Kopfzeile einfügen
Insert link = Link einfügen
Numbered list = Nummerierte Liste
Bulleted list = Aufzählung
Bold (Ctrl + B) = Fett (Strg + B)
Italic (Ctrl + I) = Kursiv (Strg + I)
Strikethrough (Ctrl + S) = Durchgestrichen (Strg + S)
No matches found = Keine Treffer gefunden
Fullscreen = Vollbild

**Comment by abaliunov-sc** [comment]
Done
[See](https://opuscapita.github.io/react-markdown//branches/enhancement(slash)internationalization/(hash)66/)

**Comment by kvolkovich-sc** [comment]
Done.
