### ISSUE TITLE
Numbered/Bulleted list behavior

### ISSUE THREAD

**Issue by hvalkova-sc** [OpusCapita/react-markdown#70]
1. When editing list and cursor goes to the next line incremented number or list marker is added for this line
2. When multiple lines of text is selected then 'list' buttons are available and allow to convert text to Numbered/Bulleted list
3. When multiple lines of list is selected then 'list' buttons are available and allow to convert Numbered/Bulleted list to simple text

**Comment by abaliunov-sc** [comment]
Done. [See](https://opuscapita.github.io/react-markdown//branches/enhancement(slash)lists-2/(hash)70/)
