### ISSUE TITLE
Autocomplete is closed after clicking on the scrollbar in IE11

### ISSUE THREAD

**Issue by jminich-sc** [OpusCapita/react-markdown#78]
Steps to reproduce:

Open https://opuscapita.github.io/react-markdown//branches/master/ in IE11
Input $
Click on the scrollbar in the opened autocomplete
![screenshot1](https://user-images.githubusercontent.com/25081565/32382249-c94cfcc8-c0c5-11e7-9eab-59666d9e5b3f.png)

Actual result: autocomplete is closed

NOTE: it has been worked properly in https://opuscapita.github.io/react-markdown//branches/bug(slash)autocomplete-2/(hash)58/?currentComponentId=%40opuscapita%2Freact-markdown%2F1.1.8%2FMarkdownInputModal&showSidebar=true

**Comment by abaliunov-sc** [comment]
Done.
See [https://opuscapita.github.io/react-markdown//branches/bug(slash)autocomplete/(hash)78/](https://opuscapita.github.io/react-markdown//branches/bug(slash)autocomplete/(hash)78/)

**Comment by kvolkovich-sc** [comment]
Fixed https://github.com/OpusCapita/react-markdown/pull/83
