### ISSUE TITLE
Text cursor disappears after pasting text in IE11

### ISSUE THREAD

**Issue by jminich-sc** [OpusCapita/react-markdown#79]
Steps to reproduce:

1. Open https://opuscapita.github.io/react-markdown//branches/master in IE11
2. Copy and past any text
3. Try to input, e.g. 'text'
Actual result: text cursor disappears

**Comment by nstoliar-sc** [comment]
Error "SCRIPT5022: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .0.0.0.0.1.3.0.0.0.0.0.0.1.0.1.0:$423.$422.$422-0. File: react-with-addons.js, Line: 20284, Column: 5" appears if try to copy some text in markdown editor.

**Comment by abaliunov-sc** [comment]
Fix.
See [https://opuscapita.github.io/react-markdown/branches/bug(slash)cursor-ie11/(hash)79](https://opuscapita.github.io/react-markdown/branches/bug(slash)cursor-ie11/(hash)79)
Please test it.

**Comment by nstoliar-sc** [comment]
Tested. Problem is not reproduced.
