### ISSUE TITLE
Change 'Fullscreen' tooltip

### ISSUE THREAD

**Issue by jminich-sc** [OpusCapita/react-markdown#80]
Please, change the tooltip to Maximize / Minimize depending on the window state
![screenshot1](https://user-images.githubusercontent.com/25081565/32404718-a31f1512-c166-11e7-963a-9da2164ddb05.png)

**Comment by jminich-sc** [comment]
@apolishchuk-sc please, provide the German translations

**Comment by apolishchuk-sc** [comment]
Maximize = Maximieren
Minimize = Minimieren

**Comment by abaliunov-sc** [comment]
Done
See [https://opuscapita.github.io/react-markdown/branches/bug(slash)fullscreen/(hash)80](https://opuscapita.github.io/react-markdown/branches/bug(slash)fullscreen/(hash)80)

**Comment by kvolkovich-sc** [comment]
Fixed https://github.com/OpusCapita/react-markdown/pull/81
