### ISSUE TITLE
Error appears if try unset numbering item list with highlighted item(s)

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#84]
1. Create some numbered (of bulleted) item list;
2. make highlighting (bold or italic) of some item;
3. highlight by cursor whole list and try to unset formation of list.
Result: error "IndexSizeError: Index or size is negative or greater than the allowed amount" appears.  Error is reproduced on Firefox and IE11.

**Comment by nstoliar-sc** [comment]
![63](https://user-images.githubusercontent.com/25082017/32660693-d9e830e2-c634-11e7-9cfb-b3bac5c615a5.png)

**Comment by abaliunov-sc** [comment]
Done. See [https://opuscapita.github.io/react-markdown//branches/master/bug(slash)unset-item-list/(hash)84](https://opuscapita.github.io/react-markdown//branches/master/bug(slash)unset-item-list/(hash)84)

**Comment by nstoliar-sc** [comment]
Bug is reproduced on master branch.

**Comment by abaliunov-sc** [comment]
Fixed.
See [https://opuscapita.github.io/react-markdown/branches/bug(slash)unset-item-list-2/(hash)84](https://opuscapita.github.io/react-markdown/branches/bug(slash)unset-item-list-2/(hash)84)
