### ISSUE TITLE
Error appears if to input empty value from autocomplete list

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#85]
1. Type some text, e.g. `text`;
2. put the cursor in middle of text;
3. click on button with autocomplete list (Product or Term);
4. sure autocomplete list shows 'No matches found' message;
5. push Enter on keyboard.
Result: Error `TypeError: item is undefined` appears. 
![64](https://user-images.githubusercontent.com/25082017/32661290-7a244b48-c637-11e7-9a74-78c1ac7ccfad.png)

**Comment by abaliunov-sc** [comment]
Done.
See [https://opuscapita.github.io/react-markdown//branches/bug(slash)autocomplete/(hash)85](https://opuscapita.github.io/react-markdown//branches/bug(slash)autocomplete/(hash)85)

**Comment by nstoliar-sc** [comment]
Bug is reproduced in IE and FF. If put "Enter" for empty search result of Terms or Products, `TypeError: item is undefined` appears in FF, and `SCRIPT5007: Unable to get property '_objectLabel' of undefined or null reference` appears in IE11.

**Comment by abaliunov-sc** [comment]
This bug is not reproduced om master branch in IE11 and FF
See [https://opuscapita.github.io/react-markdown/branches/master](https://opuscapita.github.io/react-markdown/branches/master).
