### ISSUE TITLE
Wrong setting '#' simbol while inputting product or term in link

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#86]
1. Input link form;
2. remove all symbols (including white spaces) between form brackets (between `[ ]` or `( )` );
3. put cursor between brackets;
4. try input Term or Product.
Result: symbol `#` (or `$` for terms) is set beyond brackets. 
![65](https://user-images.githubusercontent.com/25082017/32664342-011b395e-c642-11e7-8965-3cafb6f33493.png)

**Comment by abaliunov-sc** [comment]
Done.
See [https://opuscapita.github.io/react-markdown/branches/bug(slash)term-in-link/(hash)86](https://opuscapita.github.io/react-markdown/branches/bug(slash)term-in-link/(hash)86)
