### ISSUE TITLE
Highligting doesn't work if white spaces are input forward highlighted text

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#87]
![67](https://user-images.githubusercontent.com/25082017/32670665-8e852b52-c655-11e7-99c7-b90762811c62.png)

1. Open Markdown Editor;
2. input some highlighted text, e.g. ` **text** `;
3. input white spaces forward inputted text.
Result: text became not highlighted (see, attachment).

**Comment by abaliunov-sc** [comment]
It is normal behavior.
If at the beginning of a line there are 4 or more spaces, it is the indented code block. 
See [http://spec.commonmark.org/0.27/#indented-code-blocks](http://spec.commonmark.org/0.27/#indented-code-blocks)
