### ISSUE TITLE
Behavior of "Maximize" action is differ for FF and IE

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#88]
If Markdown Editor is opened in Firefox browser, "Maximize" action is made only for pop-up window area, where Markdown Editor is opened:
![76](https://user-images.githubusercontent.com/25082017/33126157-8a49d090-cf94-11e7-82e7-90285a8c0936.png)

 If Markdown Editor is opened in Internet Explorer, "Maximize" action is made for all screen area:
![77](https://user-images.githubusercontent.com/25082017/33126227-d050dc64-cf94-11e7-97d0-2f587029a849.png)

It is necessary to Maximize Markdown for all screen in Firefox, as well in Internet Explorer.

**Comment by abaliunov-sc** [comment]
Done.
See [https://opuscapita.github.io/react-markdown/branches/bug(slash)maximize/(hash)88](https://opuscapita.github.io/react-markdown/branches/bug(slash)maximize/(hash)88)
