### ISSUE TITLE
Value is not updated if new 'value' property is passed

### ISSUE THREAD

**Issue by hvalkova-sc** [OpusCapita/react-markdown#89]
Please check why editor value is not updated if new 'value' property is passed to MarkdownInput.

See example [1.1.12-DEV.PIM-12244](https://opuscapita.github.io/react-markdown//branches/1.1.12-DEV.PIM-12244/index.html)

1. Insert some value in the additional input above the editor.
2. Only when editable area is clicked, the new value is visible in the editor.
(Only happens when to input the value first time after page is loaded)

**Comment by abaliunov-sc** [comment]
Done.
See [https://opuscapita.github.io/react-markdown/branches/1.1.12-DEV.PIM-12244](https://opuscapita.github.io/react-markdown/branches/1.1.12-DEV.PIM-12244)
