### ISSUE TITLE
Text cursor disappears after selecting term/product in IE and goes to the very beginning in FF

### ISSUE THREAD

**Issue by jminich-sc** [OpusCapita/react-markdown#95]
Steps to reproduce:

- Open the https://opuscapita.github.io/react-markdown/branches/bug(slash)cursor-ie11/(hash)79/?currentComponentId=%40opuscapita%2Freact-markdown%2F1.1.13%2FMarkdownInput in FF browser
- Click on the Product/Term
- Select Product/Term

**Actual result:**
The cursor goes to the very first position

- Open the https://opuscapita.github.io/react-markdown/branches/bug(slash)cursor-ie11/(hash)79/?currentComponentId=%40opuscapita%2Freact-markdown%2F1.1.13%2FMarkdownInput in IE browser
- Click on the Product/Term
- Select Product/Term

**Actual result:**
The cursor disappears

**Comment by abaliunov-sc** [comment]
Done.
See [https://opuscapita.github.io/react-markdown/branches/bug(slash)autocomplete/(hash)95](https://opuscapita.github.io/react-markdown/branches/bug(slash)autocomplete/(hash)95)
