### ISSUE TITLE
</br> tag isn't copy under Edge

### ISSUE THREAD

**Issue by dshwedovsky-sc** [OpusCapita/react-markdown#96]
Usecase:
1. Open markdown editor
2. Copy CTRL+C some several rows like 
> blockquote _italic text_
>> blockquote **bold text**
>>> blockquotes ~~strikethrough~~
3. go to the end and insert copied text CTRL+V
4. As result text added in one row instead of 3 rows
look like
![textinedge](https://user-images.githubusercontent.com/25076735/33376764-0145608e-d520-11e7-992b-9fcd759fb729.png)

**Comment by abaliunov-sc** [comment]
Clipboard API don't work in Microsoft Edge. In current time this API has 'in development' status.
See [https://developer.microsoft.com/en-us/microsoft-edge/platform/status/clipboardapi/](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/clipboardapi/)
