### ISSUE TITLE
If click on scroll of autocomplete list in IE, user back to start of markdown

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-markdown#98]
1. Open Markdown Editor in IE11;
2. input large text;
3. input "Product" or "Term" value in end of text;
4. open autocomplete list and try to scroll list.
Result: user back to start of text.

**Comment by abaliunov-sc** [comment]
Done.
See [https://opuscapita.github.io/react-markdown/branches/bug(slash)autocomplete/(hash)98](https://opuscapita.github.io/react-markdown/branches/bug(slash)autocomplete/(hash)98).

**Comment by abaliunov-sc** [comment]
See [https://opuscapita.github.io/react-markdown/branches/bug(slash)autocomplete-2/(hash)98](https://opuscapita.github.io/react-markdown/branches/bug(slash)autocomplete-2)
